name: Terraform Security Scanning

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  security-scan:
    name: IaC Security Scan
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform


    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: terraform# updated 
